/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MaliciousSpender,
  MaliciousSpenderInterface,
} from "../../contracts/MaliciousSpender";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
    ],
    name: "canDrain",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "drain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506103c3806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806301838f931461003b578063907d985b14610050575b600080fd5b61004e6100493660046102d5565b610077565b005b61006361005e366004610318565b6101b5565b604051901515815260200160405180910390f35b6040516370a0823160e01b81526001600160a01b03838116600483015284916000918316906370a0823190602401602060405180830381865afa1580156100c2573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100e6919061034b565b9050600081116101325760405162461bcd60e51b81526020600482015260136024820152722737903130b630b731b2903a3790323930b4b760691b604482015260640160405180910390fd5b6040516323b872dd60e01b81526001600160a01b0385811660048301528481166024830152604482018390528316906323b872dd906064016020604051808303816000875af1158015610189573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101ad9190610364565b505050505050565b6040516370a0823160e01b81526001600160a01b03828116600483015260009184918391908316906370a0823190602401602060405180830381865afa158015610203573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190610227919061034b565b604051636eb1769f60e11b81526001600160a01b03868116600483015230602483015291925060009184169063dd62ed3e90604401602060405180830381865afa158015610279573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061029d919061034b565b90506000821180156102af5750818110155b9695505050505050565b80356001600160a01b03811681146102d057600080fd5b919050565b6000806000606084860312156102ea57600080fd5b6102f3846102b9565b9250610301602085016102b9565b915061030f604085016102b9565b90509250925092565b6000806040838503121561032b57600080fd5b610334836102b9565b9150610342602084016102b9565b90509250929050565b60006020828403121561035d57600080fd5b5051919050565b60006020828403121561037657600080fd5b8151801515811461038657600080fd5b939250505056fea26469706673582212205cb2ca0f12e0908e87aa00cde24fde70a80cc18cd343decddd60b2edf3c3e19864736f6c63430008140033";

type MaliciousSpenderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MaliciousSpenderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MaliciousSpender__factory extends ContractFactory {
  constructor(...args: MaliciousSpenderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MaliciousSpender & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MaliciousSpender__factory {
    return super.connect(runner) as MaliciousSpender__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaliciousSpenderInterface {
    return new Interface(_abi) as MaliciousSpenderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MaliciousSpender {
    return new Contract(address, _abi, runner) as unknown as MaliciousSpender;
  }
}
